name: Auto Release

on:
  push:
    tags:
      - 'v*' # 当有以 'v' 开头的标签推送时触发

permissions:
  contents: write
  packages: write

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: install wabt
        uses: chiefbiiko/setup-wabt@v1.0.0
        with:
          version: 1.0.12 # optional - defaults to latest wabt version

      - name: Build
        run: make build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }} is created automatically.
          draft: false
          prerelease: false

      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64